#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import sys
import tempfile
import unittest
from unittest import mock
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
LIB = ROOT / "lib"
if str(LIB) not in sys.path:
    sys.path.insert(0, str(LIB))

from agents.definitions import ensure_definitions_loaded, get_definition
from agents.jobs.broker import AgentJobBroker
from agents.jobs.store import AgentJobStore
from agents.security.actions import ActionRequest
from agents.security.broker import CapabilityBroker
from skills.test_case.dedupe import partition_new_cases
from skills.test_case.generator import generate_test_cases
from skills.test_case.models import StoryContext, TestCase
from skills.test_case.skill import generate_test_cases_for_issue, story_sheet_name


class FakeBitable:
    def __init__(self) -> None:
        self.tables = [{"table_id": "tbl1", "name": "Test Cases"}]
        self.fields = [{"field_name": name} for name, _ in (
            ("Story Key", 1),
            ("Story Title", 1),
            ("Title", 1),
            ("Steps", 1),
            ("Expected Result", 1),
            ("Type", 1),
            ("Status", 1),
            ("Source Hash", 1),
            ("Generated At", 1),
            ("Generated By", 1),
        )]
        self.views: list[dict[str, Any]] = []
        self.records: list[dict[str, Any]] = []

    def list_tables(self, app_token: str) -> list[dict[str, Any]]:
        return self.tables

    def create_table(self, app_token: str, name: str) -> dict[str, Any]:
        table = {"table_id": "tbl_new", "name": name}
        self.tables.append(table)
        return table

    def list_fields(self, app_token: str, table_id: str) -> list[dict[str, Any]]:
        return self.fields

    def create_field(self, app_token: str, table_id: str, *, name: str, field_type: int = 1, property=None) -> dict[str, Any]:
        field = {"field_name": name, "type": field_type, "property": property}
        self.fields.append(field)
        return field

    def update_field(self, app_token: str, table_id: str, field_id: str, *, name: str, field_type: int, property=None) -> dict[str, Any]:
        field = {"field_name": name, "field_id": field_id, "type": field_type, "property": property}
        self.fields.append(field)
        return field

    def list_views(self, app_token: str, table_id: str) -> list[dict[str, Any]]:
        return self.views

    def create_view(self, app_token: str, table_id: str, *, name: str, view_type: str = "grid") -> dict[str, Any]:
        view = {"view_name": name, "view_type": view_type}
        self.views.append(view)
        return view

    def list_records(self, app_token: str, table_id: str, *, page_size: int = 100) -> list[dict[str, Any]]:
        return list(self.records)

    def create_record(self, app_token: str, table_id: str, fields: dict[str, Any]) -> dict[str, Any]:
        record = {"record_id": f"rec{len(self.records)+1}", "fields": dict(fields)}
        self.records.append(record)
        return record


class FakeSheets:
    def __init__(self) -> None:
        self.rows: list[list[Any]] = []
        self.appended: list[list[Any]] = []
        self.ensured_names: list[str] = []
        self.dropdowns: list[dict[str, Any]] = []
        self.formatted: list[dict[str, Any]] = []
        self.styles: list[dict[str, Any]] = []

    def ensure_sheet(self, spreadsheet_token: str, sheet_name: str) -> dict[str, Any]:
        self.ensured_names.append(sheet_name)
        return {"sheetId": "sht1", "title": sheet_name}

    def resolve_sheet(self, spreadsheet_token: str, sheet_name: str = "Sheet1") -> dict[str, Any]:
        return {"sheetId": "sht1", "title": sheet_name}

    def get_values(self, spreadsheet_token: str, range_a1: str) -> list[list[Any]]:
        return list(self.rows)

    def append_values(self, spreadsheet_token: str, *, sheet_id: str, values: list[list[Any]], start_col: str = "A", end_col: str = "J") -> dict[str, Any]:
        for row in values:
            self.rows.append(list(row))
            self.appended.append(list(row))
        return {"updatedRows": len(values)}

    def set_dropdown(self, spreadsheet_token: str, *, sheet_id: str, range_a1: str, options: list[str], colors=None) -> dict[str, Any]:
        self.dropdowns.append({"sheet_id": sheet_id, "range_a1": range_a1, "options": list(options), "colors": list(colors or [])})
        return {}

    def set_range_style(self, spreadsheet_token: str, *, sheet_id: str, range_a1: str, bold: bool | None = None, v_align: int | None = None, back_color=None, fore_color=None, h_align=None, border_type=None, border_color=None, font_size=None) -> dict[str, Any]:
        self.styles.append({"sheet_id": sheet_id, "range_a1": range_a1, "bold": bold, "v_align": v_align, "back_color": back_color, "fore_color": fore_color, "border_type": border_type, "border_color": border_color, "font_size": font_size})
        return {}

    def format_sheet(
        self,
        spreadsheet_token: str,
        *,
        sheet_id: str,
        column_widths=None,
        freeze_rows: int = 1,
        bold_header: bool = False,
        header_end_col: str = "",
        body_row_height: int = 96,
    ) -> dict[str, Any]:
        self.formatted.append(
            {
                "sheet_id": sheet_id,
                "column_widths": list(column_widths or []),
                "freeze_rows": freeze_rows,
                "bold_header": bold_header,
                "header_end_col": header_end_col,
                "body_row_height": body_row_height,
            }
        )
        if bold_header:
            self.set_range_style(
                spreadsheet_token,
                sheet_id=sheet_id,
                range_a1=f"A1:{(header_end_col or 'A')}1",
                bold=True,
            )
        return {}

def _mock_design_runner(payload: dict[str, Any]):
    def _runner(_prompt: str) -> str:
        return json.dumps(payload, ensure_ascii=False)

    return _runner


LOGIN_DESIGN = {
    "test_cases": [
        {
            "ac_refs": ["AC1"],
            "title": "使用 Email 成功登入",
            "preconditions": ["使用者帳號已啟用。"],
            "steps": ["開啟登入頁。", "輸入正確 Email 與密碼並提交。"],
            "expected_results": ["成功進入首頁。"],
            "case_type": "functional",
            "rationale": "login happy path",
        },
        {
            "ac_refs": ["AC1"],
            "title": "錯誤密碼時顯示登入失敗",
            "preconditions": ["使用者帳號已啟用。"],
            "steps": ["開啟登入頁。", "輸入正確 Email 與錯誤密碼並提交。"],
            "expected_results": ["顯示登入失敗提示且不進入首頁。"],
            "case_type": "validation",
            "rationale": "invalid password",
        },
        {
            "ac_refs": ["AC1"],
            "title": "登入頁顯示登入表單",
            "preconditions": ["未登入狀態。"],
            "steps": ["開啟登入頁。"],
            "expected_results": ["顯示 Email、密碼欄位與提交按鈕。"],
            "case_type": "ui",
            "rationale": "login form visible",
        },
    ]
}


class TestCaseSkillTests(unittest.TestCase):
    def test_workspace_layout_merges_global_ai_and_agent_sheet_config(self) -> None:
        fake = FakeSheets()
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "lumon" / "config").mkdir(parents=True)
            (root / "lumon" / "config" / "common.json").write_text(
                json.dumps({"execution": {"provider": "deepseek", "model": "deepseek-v4-flash"}}),
                encoding="utf-8",
            )
            agents_home = root / "agents"
            agents_home.mkdir()
            (agents_home / "config.json").write_text(
                json.dumps(
                    {
                        "projects": {
                            "mbpass": {
                                "test_case": {
                                    "destination": "sheet",
                                    "spreadsheet_token": "OG4Js7cIlh7d0QtHOEnc1kDfnvf",
                                    "sheet_name": "Sheet1",
                                }
                            }
                        }
                    }
                ),
                encoding="utf-8",
            )
            with mock.patch.dict(os.environ, {"LUMEN_AGENTS_HOME": str(agents_home)}):
                result = generate_test_cases_for_issue(
                    project="mbpass",
                    issue_key="MBPAS-1601",
                    workspace=root,
                    config=None,
                    sheets_client=fake,
                    story_reader=lambda key: StoryContext(
                        key=key,
                        type="Story",
                        summary="Login flow",
                        description="",
                        acceptance_criteria=["User can log in"],
                    ),
                    designer_runner=_mock_design_runner(LOGIN_DESIGN),
                )

        self.assertEqual(result["status"], "completed")
        self.assertGreaterEqual(result["created"], 3)

    def test_designer_uses_global_opencode_provider(self) -> None:
        from skills.test_case.designer import design_test_cases

        story = StoryContext(
            key="MBPAS-1601",
            type="Story",
            summary="Login flow",
            description="desc",
            acceptance_criteria=["User can log in with email"],
        )
        with mock.patch(
            "skills.test_case.designer._run_opencode_agent",
            return_value=json.dumps(LOGIN_DESIGN, ensure_ascii=False),
        ) as completion:
            drafts = design_test_cases(
                story,
                agents_config={
                    "execution": {
                        "provider": "opencode",
                        "model": "deepseek-v4-flash",
                        "api_key_env": "DEEPSEEK_API_KEY",
                    }
                },
            )

        self.assertEqual(3, len(drafts))
        self.assertEqual("deepseek-v4-flash", completion.call_args.kwargs["model"])

    def test_generator_covers_ac_types(self) -> None:
        story = StoryContext(
            key="MBPAS-1601",
            type="Story",
            summary="Login flow",
            description="desc",
            acceptance_criteria=["User can log in with email", "Invalid password is rejected"],
        )
        cases = generate_test_cases(story)
        types = {c.case_type for c in cases}
        self.assertEqual(types, {"functional", "validation", "boundary"})
        self.assertGreaterEqual(len(cases), 6)
        for case in cases:
            self.assertTrue(case.title)
            self.assertTrue(case.steps)
            self.assertTrue(case.expected_result)
            self.assertFalse(case.title.startswith(story.key))
            fields = case.to_sheet_fields("zh-Hant")
            self.assertEqual(
                list(fields),
                ["AC", "Title", "Preconditions", "Steps", "Expected Result", "Type", "Verify Status", "Note"],
            )
        zh = generate_test_cases(story, language="zh-Hant")
        self.assertTrue(any("正常路徑" in c.title for c in zh))
        self.assertEqual(story_sheet_name("MBPAS-1", "Hello"), "MBPAS-1 · Hello")

    def test_jira_ac_blocks_ignore_summary_header(self) -> None:
        from skills.test_case.jira_read import _extract_acceptance_criteria

        description = (
            "Summary\n：後台新增活動Banner\n"
            "Background\n：需要後台管理\n"
            "AC 1：左側選單新增入口\nGiven Admin登入\nWhen 檢視選單\nThen 出現入口\n"
            'AC 2：列表支援狀態篩選\n{"type": "hardBreak"}\nGiven 進入列表\nThen 可篩選'
        )
        criteria = _extract_acceptance_criteria(description, {})
        self.assertEqual(len(criteria), 2)
        self.assertTrue(criteria[0].startswith("AC1:"))
        self.assertIn("左側選單", criteria[0])
        self.assertNotIn("Summary", criteria[0])

    def test_dedupe_skips_existing_titles(self) -> None:
        generated = [
            TestCase("A", "1", "ok", "functional", "MBPAS-1", "t"),
            TestCase("B", "1", "ok", "functional", "MBPAS-1", "t"),
            TestCase("a", "1", "ok", "functional", "MBPAS-1", "t"),
        ]
        created, skipped = partition_new_cases(generated, {"A"})
        self.assertEqual([c.title for c in created], ["B"])
        self.assertEqual(len(skipped), 2)

    def test_skill_writes_additive_rows(self) -> None:
        fake = FakeBitable()
        fake.records.append({"fields": {"Story Key": "MBPAS-1601", "Title": "使用 Email 成功登入"}})

        def reader(key: str) -> StoryContext:
            return StoryContext(
                key=key,
                type="Story",
                summary="Login flow",
                description="",
                acceptance_criteria=["User can log in"],
            )

        result = generate_test_cases_for_issue(
            project="mbpass",
            issue_key="MBPAS-1601",
            config={"projects": {"mbpass": {"test_case": {"base_app_token": "bas_test", "table_name": "Test Cases", "language": "zh-Hant"}}}},
            client=fake,
            story_reader=reader,
            designer_runner=_mock_design_runner(LOGIN_DESIGN),
        )
        self.assertEqual(result["status"], "completed")
        self.assertGreaterEqual(result["created"], 2)
        self.assertGreaterEqual(result["skipped_existing"], 1)
        self.assertIn("MBPAS-1601", result["view_name"])
        self.assertTrue(result["summary"])

    def test_skill_writes_spreadsheet_rows(self) -> None:
        fake = FakeSheets()

        def reader(key: str) -> StoryContext:
            return StoryContext(
                key=key,
                type="Story",
                summary="Login flow",
                description="",
                acceptance_criteria=["User can log in"],
            )

        result = generate_test_cases_for_issue(
            project="mbpass",
            issue_key="MBPAS-1601",
            config={
                "projects": {
                    "mbpass": {
                        "test_case": {
                            "destination": "sheet",
                            "spreadsheet_token": "OG4Js7cIlh7d0QtHOEnc1kDfnvf",
                            "sheet_name": "Sheet1",
                            "language": "zh-Hant",
                        }
                    }
                }
            },
            sheets_client=fake,
            story_reader=reader,
            designer_runner=_mock_design_runner(LOGIN_DESIGN),
        )
        self.assertEqual(result["status"], "completed")
        self.assertGreaterEqual(result["created"], 3)
        self.assertEqual(fake.ensured_names, ["MBPAS-1601 · Login flow"])
        self.assertEqual(result["view_name"], "MBPAS-1601 · Login flow")
        self.assertEqual(
            fake.rows[0],
            ["AC", "Title", "Preconditions", "Steps", "Expected Result", "Type", "Verify Status", "Note"],
        )
        for row in fake.rows[1:]:
            self.assertFalse(str(row[1]).startswith("MBPAS-1601"))
            self.assertEqual(len(row), 8)
            self.assertIn(row[5], {"功能", "驗證", "介面"})
            self.assertEqual(row[6], "待驗證")
            self.assertEqual(row[7], "")
        self.assertEqual(fake.dropdowns[0]["options"], ["待驗證", "驗證成功", "驗證失敗", "忽略"])
        self.assertEqual(fake.dropdowns[0]["colors"], ["#A3D0D6", "#B5CFBC", "#F9B0BD", "#E6C284"])
        self.assertIn("G2:G2000", fake.dropdowns[0]["range_a1"])
        self.assertTrue(fake.formatted)
        self.assertTrue(fake.formatted[0]["bold_header"])
        self.assertEqual(fake.formatted[0]["header_end_col"], "H")
        self.assertEqual(fake.formatted[0]["body_row_height"], 96)
        self.assertTrue(any(s.get("bold") and s.get("range_a1") == "A1:H1" for s in fake.styles))
        self.assertIn("/sheets/OG4Js7cIlh7d0QtHOEnc1kDfnvf?sheet=sht1", result["sheet_url"])

    def test_broker_test_case_action_uses_request_agent_identity(self) -> None:
        ensure_definitions_loaded()
        mark = get_definition("mark")
        milchick = get_definition("milchick")
        assert mark is not None and milchick is not None
        self.assertNotIn("test_case.generate", mark.capabilities.actions)
        self.assertIn("test_case.generate", milchick.capabilities.actions)
        from unittest import mock

        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch.dict(os.environ, {"LUMEN_AGENTS_HOME": tmp}):
                with mock.patch("skills.test_case.skill.generate_test_cases_for_issue") as gen:
                    gen.return_value = {"status": "completed", "summary": "ok", "created": 1, "generated": 1}
                    broker = CapabilityBroker(
                        config={
                            "access": {
                                "allowed_chat_ids": ["oc1"],
                                "allowed_user_ids": ["ou_owner"],
                                "mutation_allowed_user_ids": ["ou_owner"],
                            }
                        }
                    )
                    for agent_id in ("milchick",):
                        receipt = broker.execute(
                            ActionRequest(
                                agent_id=agent_id,
                                action="test_case.generate",
                                project_slug="mbpass",
                                actor_user_id="ou_owner",
                                chat_id="oc1",
                                thread_id="",
                                source_message_id="om1",
                                trace_id="tr1",
                                resource={"issue_key": "MBPAS-1601"},
                                arguments={"issue_key": "MBPAS-1601", "chat_type": "group"},
                                explicit_authorization=True,
                            )
                        )
                        self.assertEqual(receipt.status, "succeeded")
                        self.assertEqual(gen.call_args.kwargs["generated_by"], agent_id)

    def test_scoped_test_case_action_queries_and_processes_each_story(self) -> None:
        from agents.security.adapters.test_case import execute_test_case_action

        request = ActionRequest(
            agent_id="milchick",
            action="test_case.generate",
            project_slug="mbpass",
            actor_user_id="ou_owner",
            chat_id="oc1",
            thread_id="omt1",
            source_message_id="om1",
            trace_id="tr1",
            arguments={"scope": "ready_for_qa"},
        )
        with mock.patch(
            "agents.security.adapters.jira._action_jira_config",
            return_value={"project_key": "MBPAS"},
        ), mock.patch(
            "agents.security.adapters.jira._query_workitems",
            return_value={
                "status": "completed",
                "items": [
                    {"issue_key": "MBPAS-1", "summary": "First"},
                    {"issue_key": "MBPAS-2", "summary": "Second"},
                ],
            },
        ), mock.patch(
            "skills.test_case.skill.generate_test_cases_for_issue",
            side_effect=[
                {"status": "completed", "generated": 2, "created": 2, "sheet_url": "https://sheet/1"},
                {"status": "failed", "code": "TEST_CASE_CONFIG_MISSING", "message": "missing sheet"},
            ],
        ) as generate:
            result = execute_test_case_action(request)

        self.assertEqual("partial", result["status"])
        self.assertEqual(2, result["count"])
        self.assertEqual(1, result["completed"])
        self.assertEqual(1, result["failed"])
        self.assertEqual(["MBPAS-1", "MBPAS-2"], [item["issue_key"] for item in result["items"]])
        self.assertEqual(2, generate.call_count)

    def test_scoped_query_is_story_only(self) -> None:
        from agents.security.adapters.test_case import execute_test_case_action

        request = ActionRequest(
            agent_id="milchick",
            action="test_case.generate",
            project_slug="mbpass",
            actor_user_id="ou_owner",
            chat_id="oc1",
            thread_id="omt1",
            source_message_id="om1",
            trace_id="tr1",
            arguments={"scope": "ready_for_qa"},
        )
        with mock.patch(
            "agents.security.adapters.test_case._docs_root",
            return_value=Path("/tmp/workspace"),
        ), mock.patch(
            "agents.security.adapters.jira._action_jira_config",
            return_value={"project_key": "MBPAS"},
        ), mock.patch(
            "agents.security.adapters.jira._query_workitems",
            return_value={"status": "completed", "items": []},
        ) as query:
            execute_test_case_action(request)

        self.assertIn('issuetype = "Story"', query.call_args.kwargs["jql"])


class MilchickJobTests(unittest.TestCase):
    def test_technical_loop_waits_for_artifact_instead_of_claiming_completion(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            docs = Path(tmp) / "docs"
            story = docs / "stories" / "MBPAS-1503-recommendations"
            story.mkdir(parents=True)
            (story / "story.md").write_text("# MBPAS-1503\n", encoding="utf-8")
            (story / "metadata.json").write_text(
                json.dumps({"jiraKey": "MBPAS-1503", "businessStatus": "ready", "technicalStatus": "draft"}),
                encoding="utf-8",
            )
            from agents.mark.delivery_adapter import DeliveryActionAdapter

            state = DeliveryActionAdapter().loop_state(
                workspace=docs,
                story="MBPAS-1503",
                capability="loop.technical",
            )
            self.assertFalse(state["complete"])
            self.assertEqual("technical_plan_missing", state["reason"])

    def test_waiting_user_loop_is_visible_in_parent_summary(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            store = AgentJobStore(Path(tmp) / "jobs.sqlite3")
            broker = AgentJobBroker(store)
            parent = broker.create_parent(
                project="mbpass", requested_by="ou_owner", delegated_by="milchick",
                source_message_id="om1", chat_id="oc1", thread_id="omt1", trace_id="tr1",
            )
            child = broker.create_child(
                parent=parent, target_agent="mark", capability="loop.technical",
                input_data={"issue_key": "MBPAS-1503"},
            )
            child.status = "waiting_user"
            child.result = {"result": {"question": "Which repository should be used?"}}
            store.save(child)
            summary = broker.summarize(parent.job_id)
            self.assertEqual("waiting_user", summary["overall_state"])
            self.assertIn(child.job_id, summary["waiting_user"])

    def test_waiting_loop_matches_mark_question_reply_anchor(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            store = AgentJobStore(Path(tmp) / "jobs.sqlite3")
            parent = AgentJobBroker(store).create_parent(
                project="mbpass", requested_by="ou_owner", delegated_by="milchick",
                source_message_id="om-root", chat_id="oc1", thread_id="", trace_id="tr1",
            )
            child = AgentJobBroker(store).create_child(
                parent=parent, target_agent="mark", capability="loop.technical",
                input_data={"issue_key": "MBPAS-1503"},
            )
            child.status = "waiting_user"
            child.result = {"question_message_id": "om-question"}
            store.save(child)
            found = store.find_waiting_loop(
                agent_id="mark", chat_id="oc1", parent_id="om-question",
            )
            self.assertIsNotNone(found)
            self.assertEqual(child.job_id, found.job_id)
    def test_milchick_definition_registered(self) -> None:
        ensure_definitions_loaded()
        milchick = get_definition("milchick")
        assert milchick is not None
        self.assertEqual(milchick.role, "orchestrator")
        self.assertIn("agent.job.create", milchick.capabilities.actions)
        self.assertIn("jira.workitem.create", milchick.capabilities.actions)
        self.assertIn("test_case.generate", milchick.capabilities.actions)

    def test_job_dependency_and_summary(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            store = AgentJobStore(Path(tmp) / "jobs.sqlite3")
            broker = AgentJobBroker(store)
            parent = broker.create_parent(
                project="mbpass",
                requested_by="ou_owner",
                delegated_by="milchick",
                source_message_id="om1",
                chat_id="oc1",
                thread_id="th1",
                trace_id="tr1",
            )
            first = broker.create_child(
                parent=parent,
                target_agent="irving",
                capability="risk.resolve",
                input_data={"finding_id": "FIND-1"},
            )
            second = broker.create_child(
                parent=parent,
                target_agent="milchick",
                capability="test_case.generate",
                input_data={"issue_key": "MBPAS-1601"},
                depends_on=[first.job_id],
            )
            self.assertEqual(first.status, "ready")
            self.assertEqual(second.status, "queued")
            first.status = "completed"
            store.save(first)
            broker.refresh_dependencies(parent.job_id)
            second = store.get(second.job_id)
            assert second is not None
            self.assertEqual(second.status, "ready")
            summary = broker.summarize(parent.job_id)
            self.assertIn(summary["overall_state"], {"running", "completed", "blocked"})

    def test_quick_change_handoff_preserves_original_turn(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            store = AgentJobStore(Path(tmp) / "jobs.sqlite3")
            broker = AgentJobBroker(store)
            parent = broker.create_parent(
                project="mbpass",
                requested_by="ou_owner",
                delegated_by="milchick",
                source_message_id="om1",
                chat_id="oc1",
                thread_id="",
                trace_id="tr1",
            )
            child = broker.create_child(
                parent=parent,
                target_agent="mark",
                capability="delivery.quick_change",
                input_data={
                    "user_message": "Admin Portal 中的 Wording「輪播圖」改成「多圖」",
                    "image_keys": '["img_v3"]',
                    "chat_type": "group",
                },
            )
            with mock.patch(
                "agents.bridge.handle_agent_message",
                return_value={"status": "ok", "text": "Mark started the bounded change."},
            ) as handoff, mock.patch(
                "feishu.messenger.FeishuMessenger.safe_reply_text",
                return_value={"message_id": "om2"},
            ):
                completed = broker.execute_ready_child(child)

            self.assertEqual("completed", completed.status)
            handoff.assert_called_once()
            kwargs = handoff.call_args.kwargs
            self.assertEqual("mark", kwargs["agent_id"])
            self.assertIn("This task is handed to you", kwargs["text"])
            self.assertIn(child.input["user_message"], kwargs["text"])
            self.assertEqual("mbpass", kwargs["meta"]["_project_slug"])
            self.assertEqual('["img_v3"]', kwargs["meta"]["image_keys"])
            self.assertEqual("1", kwargs["meta"]["_nested_handoff"])
            self.assertEqual("1", kwargs["meta"]["_new_agent_turn"])

    def test_loop_handoff_preserves_original_turn(self) -> None:
        for capability in ("loop.business", "loop.technical"):
            with self.subTest(capability=capability):
                with tempfile.TemporaryDirectory() as tmp:
                    store = AgentJobStore(Path(tmp) / "jobs.sqlite3")
                    broker = AgentJobBroker(store)
                    parent = broker.create_parent(
                        project="mbpass",
                        requested_by="ou_owner",
                        delegated_by="milchick",
                        source_message_id="om1",
                        chat_id="oc1",
                        thread_id="",
                        trace_id="tr1",
                    )
                    child = broker.create_child(
                        parent=parent,
                        target_agent="mark",
                        capability=capability,
                        input_data={
                            "user_message": "把 MBPAS-1503 進行 Technical Plan",
                            "image_keys": '["img_v3"]',
                            "chat_type": "group",
                        },
                    )
                    with mock.patch(
                        "agents.bridge.handle_agent_message",
                        return_value={"status": "ok", "text": "Mark started the loop."},
                    ) as handoff, mock.patch(
                        "feishu.messenger.FeishuMessenger.safe_reply_text",
                        return_value={"message_id": "om2"},
                    ):
                        completed = broker.execute_ready_child(child)

                    self.assertEqual("waiting_user", completed.status)
                    handoff.assert_called_once()
                    kwargs = handoff.call_args.kwargs
                    self.assertEqual("mark", kwargs["agent_id"])
                    self.assertIn("[ORIGINAL USER INPUT]", kwargs["text"])
                    self.assertIn(child.input["user_message"], kwargs["text"])
                    expected_hint = "Business Loop" if capability == "loop.business" else "Technical Loop"
                    self.assertIn(expected_hint, kwargs["text"])
                    self.assertEqual("1", kwargs["meta"]["_nested_handoff"])


if __name__ == "__main__":
    unittest.main()
