#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import sys
import tempfile
import unittest
from unittest import mock
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
LIB = ROOT / "lib"
if str(LIB) not in sys.path:
    sys.path.insert(0, str(LIB))

from agents.definitions import ensure_definitions_loaded, get_definition
from agents.jobs.broker import AgentJobBroker
from agents.jobs.store import AgentJobStore
from agents.security.actions import ActionRequest
from agents.security.broker import CapabilityBroker
from skills.test_case.dedupe import partition_new_cases
from skills.test_case.feature_point import infer_common_surface, normalize_feature_point
from skills.test_case.generator import generate_test_cases
from skills.test_case.models import StoryContext, TestCase
from skills.test_case.skill import generate_test_cases_for_issue, pk03_path_for_case_type, story_sheet_name


class FakeBitable:
    def __init__(self) -> None:
        self.tables = [{"table_id": "tbl1", "name": "Test Cases"}]
        self.fields = [{"field_name": name} for name, _ in (
            ("Story Key", 1),
            ("Story Title", 1),
            ("Title", 1),
            ("Steps", 1),
            ("Expected Result", 1),
            ("Type", 1),
            ("Status", 1),
            ("Source Hash", 1),
            ("Generated At", 1),
            ("Generated By", 1),
        )]
        self.views: list[dict[str, Any]] = []
        self.records: list[dict[str, Any]] = []

    def list_tables(self, app_token: str) -> list[dict[str, Any]]:
        return self.tables

    def create_table(self, app_token: str, name: str) -> dict[str, Any]:
        table = {"table_id": "tbl_new", "name": name}
        self.tables.append(table)
        return table

    def list_fields(self, app_token: str, table_id: str) -> list[dict[str, Any]]:
        return self.fields

    def create_field(self, app_token: str, table_id: str, *, name: str, field_type: int = 1, property=None) -> dict[str, Any]:
        field = {"field_name": name, "type": field_type, "property": property}
        self.fields.append(field)
        return field

    def update_field(self, app_token: str, table_id: str, field_id: str, *, name: str, field_type: int, property=None) -> dict[str, Any]:
        field = {"field_name": name, "field_id": field_id, "type": field_type, "property": property}
        self.fields.append(field)
        return field

    def list_views(self, app_token: str, table_id: str) -> list[dict[str, Any]]:
        return self.views

    def create_view(self, app_token: str, table_id: str, *, name: str, view_type: str = "grid") -> dict[str, Any]:
        view = {"view_name": name, "view_type": view_type}
        self.views.append(view)
        return view

    def list_records(self, app_token: str, table_id: str, *, page_size: int = 100) -> list[dict[str, Any]]:
        return list(self.records)

    def create_record(self, app_token: str, table_id: str, fields: dict[str, Any]) -> dict[str, Any]:
        record = {"record_id": f"rec{len(self.records)+1}", "fields": dict(fields)}
        self.records.append(record)
        return record


class FakeSheets:
    def __init__(self) -> None:
        self.rows: list[list[Any]] = []
        self.grid_rows = 120
        self.ensured_names: list[str] = []
        self.copied: list[dict[str, Any]] = []
        self.cleared: list[dict[str, Any]] = []
        self.writes: list[dict[str, Any]] = []
        self.dropdowns: list[dict[str, Any]] = []
        self.formatted: list[dict[str, Any]] = []
        self.styles: list[dict[str, Any]] = []
        self.verified: list[dict[str, Any]] = []

    def list_sheets(self, spreadsheet_token: str) -> list[dict[str, Any]]:
        sheets = [{"sheetId": "pk03", "title": "PK03"}]
        sheets.extend(self.copied)
        return sheets

    def ensure_sheet(self, spreadsheet_token: str, sheet_name: str) -> dict[str, Any]:
        self.ensured_names.append(sheet_name)
        return {"sheetId": "sht1", "title": sheet_name}

    def copy_sheet(self, spreadsheet_token: str, *, source_sheet_id: str, title: str, index: int | None = None) -> dict[str, Any]:
        sheet = {"sheetId": f"sht{len(self.copied) + 1}", "title": title}
        self.copied.append(sheet)
        return sheet

    def resolve_sheet(self, spreadsheet_token: str, sheet_name: str = "Sheet1") -> dict[str, Any]:
        return {"sheetId": "sht1", "title": sheet_name}

    def get_sheet_row_count(self, spreadsheet_token: str, *, sheet_id: str) -> int:
        return self.grid_rows

    def get_values(self, spreadsheet_token: str, range_a1: str) -> list[list[Any]]:
        return list(self.rows)

    def clear_values(self, spreadsheet_token: str, *, sheet_id: str, range_a1: str) -> dict[str, Any]:
        self.cleared.append({"sheet_id": sheet_id, "range_a1": range_a1})
        self.rows = []
        return {}

    def set_values(self, spreadsheet_token: str, *, sheet_id: str, range_a1: str, values: list[list[Any]]) -> dict[str, Any]:
        start_row = int(range_a1.split(":", 1)[0][1:])
        while len(self.rows) < start_row - 1:
            self.rows.append([])
        for offset, row in enumerate(values):
            row_index = start_row - 1 + offset
            while len(self.rows) <= row_index:
                self.rows.append([])
            self.rows[row_index] = list(row)
        self.writes.append({"sheet_id": sheet_id, "range_a1": range_a1, "values": [list(row) for row in values]})
        return {}

    def set_dropdown(self, spreadsheet_token: str, *, sheet_id: str, range_a1: str, options: list[str], colors=None) -> dict[str, Any]:
        self.dropdowns.append({"sheet_id": sheet_id, "range_a1": range_a1, "options": list(options), "colors": list(colors or [])})
        return {}

    def set_range_style(self, spreadsheet_token: str, *, sheet_id: str, range_a1: str, bold: bool | None = None, v_align: int | None = None, back_color=None, fore_color=None, h_align=None, border_type=None, border_color=None, font_size=None) -> dict[str, Any]:
        self.styles.append({"sheet_id": sheet_id, "range_a1": range_a1, "bold": bold, "v_align": v_align, "back_color": back_color, "fore_color": fore_color, "border_type": border_type, "border_color": border_color, "font_size": font_size})
        return {}

    def format_sheet(
        self,
        spreadsheet_token: str,
        *,
        sheet_id: str,
        column_widths=None,
        freeze_rows: int = 1,
        bold_header: bool = False,
        header_end_col: str = "",
        body_row_height: int = 96,
        body_end_row: int | None = None,
    ) -> dict[str, Any]:
        self.formatted.append(
            {
                "sheet_id": sheet_id,
                "column_widths": list(column_widths or []),
                "freeze_rows": freeze_rows,
                "bold_header": bold_header,
                "header_end_col": header_end_col,
                "body_row_height": body_row_height,
            }
        )
        if bold_header:
            self.set_range_style(
                spreadsheet_token,
                sheet_id=sheet_id,
                range_a1=f"A1:{(header_end_col or 'A')}1",
                bold=True,
            )
        return {}

    def verify_sheet_format(self, spreadsheet_token: str, *, sheet_id: str, freeze_rows: int, validation_range: str, validation_options: list[str]) -> dict[str, Any]:
        self.verified.append(
            {
                "sheet_id": sheet_id,
                "freeze_rows": freeze_rows,
                "validation_range": validation_range,
                "validation_options": list(validation_options),
            }
        )
        return {}

def _mock_design_runner(payload: dict[str, Any]):
    def _runner(_prompt: str) -> str:
        return json.dumps(payload, ensure_ascii=False)

    return _runner


LOGIN_DESIGN = {
    "test_cases": [
        {
            "ac_refs": ["AC1"],
            "title": "使用 Email 成功登入",
            "preconditions": ["使用者帳號已啟用。"],
            "steps": ["開啟登入頁。", "輸入正確 Email 與密碼並提交。"],
            "expected_results": ["成功進入首頁。"],
            "case_type": "functional",
            "feature_point": "App",
            "rationale": "login happy path",
        },
        {
            "ac_refs": ["AC1"],
            "title": "錯誤密碼時顯示登入失敗",
            "preconditions": ["使用者帳號已啟用。"],
            "steps": ["開啟登入頁。", "輸入正確 Email 與錯誤密碼並提交。"],
            "expected_results": ["顯示登入失敗提示且不進入首頁。"],
            "case_type": "validation",
            "feature_point": "App",
            "rationale": "invalid password",
        },
        {
            "ac_refs": ["AC1"],
            "title": "登入頁顯示登入表單",
            "preconditions": ["未登入狀態。"],
            "steps": ["開啟登入頁。"],
            "expected_results": ["顯示 Email、密碼欄位與提交按鈕。"],
            "case_type": "ui",
            "feature_point": "App",
            "rationale": "login form visible",
        },
    ]
}


class TestCaseSkillTests(unittest.TestCase):
    def test_workspace_layout_merges_global_ai_and_agent_sheet_config(self) -> None:
        fake = FakeSheets()
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "lumon" / "config").mkdir(parents=True)
            (root / "lumon" / "config" / "common.json").write_text(
                json.dumps({"execution": {"provider": "deepseek", "model": "deepseek-v4-flash"}}),
                encoding="utf-8",
            )
            agents_home = root / "agents"
            agents_home.mkdir()
            (agents_home / "config.json").write_text(
                json.dumps(
                    {
                        "projects": {
                            "mbpass": {
                                "test_case": {
                                    "destination": "sheet",
                                    "spreadsheet_token": "test-a-spreadsheet",
                                    "sheet_name": "PK03",
                                    "sheet_template_id": "pk03-template",
                                }
                            }
                        }
                    }
                ),
                encoding="utf-8",
            )
            with mock.patch.dict(os.environ, {"LUMEN_AGENTS_HOME": str(agents_home)}):
                result = generate_test_cases_for_issue(
                    project="mbpass",
                    issue_key="MBPAS-1601",
                    workspace=root,
                    config=None,
                    sheets_client=fake,
                    story_reader=lambda key: StoryContext(
                        key=key,
                        type="Story",
                        summary="Login flow",
                        description="",
                        acceptance_criteria=["User can log in"],
                    ),
                    designer_runner=_mock_design_runner(LOGIN_DESIGN),
                )

        self.assertEqual(result["status"], "completed")
        self.assertGreaterEqual(result["created"], 3)

    def test_designer_uses_global_opencode_provider(self) -> None:
        from skills.test_case.designer import design_test_cases

        story = StoryContext(
            key="MBPAS-1601",
            type="Story",
            summary="Login flow",
            description="desc",
            acceptance_criteria=["User can log in with email"],
        )
        with mock.patch(
            "skills.test_case.designer._run_opencode_agent",
            return_value=json.dumps(LOGIN_DESIGN, ensure_ascii=False),
        ) as completion:
            drafts = design_test_cases(
                story,
                agents_config={
                    "execution": {
                        "provider": "opencode",
                        "model": "deepseek-v4-flash",
                        "api_key_env": "DEEPSEEK_API_KEY",
                    }
                },
            )

        self.assertEqual(3, len(drafts))
        self.assertEqual("deepseek-v4-flash", completion.call_args.kwargs["model"])

    def test_generator_covers_ac_types(self) -> None:
        story = StoryContext(
            key="MBPAS-1601",
            type="Story",
            summary="Login flow",
            description="desc",
            acceptance_criteria=["User can log in with email", "Invalid password is rejected"],
        )
        cases = generate_test_cases(story)
        types = {c.case_type for c in cases}
        self.assertEqual(types, {"functional", "validation", "boundary"})
        self.assertGreaterEqual(len(cases), 6)
        for case in cases:
            self.assertTrue(case.title)
            self.assertTrue(case.steps)
            self.assertTrue(case.expected_result)
            self.assertFalse(case.title.startswith(story.key))
            fields = case.to_sheet_fields("zh-Hant")
            self.assertEqual(
                list(fields),
                ["AC", "Title", "Preconditions", "Steps", "Expected Result", "Type", "Verify Status", "Note"],
            )
        zh = generate_test_cases(story, language="zh-Hant")
        self.assertTrue(any("正常路徑" in c.title for c in zh))
        self.assertEqual(story_sheet_name("MBPAS-1", "Hello"), "MBPAS-1 · Hello")

    def test_pk03_path_uses_case_type_categories(self) -> None:
        self.assertEqual(pk03_path_for_case_type("functional"), "Happy")
        self.assertEqual(pk03_path_for_case_type("filter"), "Alternative")
        self.assertEqual(pk03_path_for_case_type("validation"), "Sad")
        self.assertEqual(pk03_path_for_case_type("boundary"), "Sad(Edge)")

    def test_pk03_feature_point_uses_project_agnostic_surface_evidence(self) -> None:
        self.assertEqual(infer_common_surface("後台管理頁面"), "Admin Portal")
        self.assertEqual(infer_common_surface("App article detail"), "App")
        self.assertEqual(infer_common_surface("mobile client"), "Mobile App")
        self.assertEqual(infer_common_surface("audience count API"), "API/Backend")
        self.assertEqual(normalize_feature_point("project-specific console", "unknown story"), "project-specific console")

    def test_generator_falls_back_to_common_surface_instead_of_story_title(self) -> None:
        story = StoryContext(
            key="DEMO-1",
            type="Story",
            summary="Admin Portal audience filter",
            description="",
            acceptance_criteria=["The admin portal filters the audience"],
        )
        cases = generate_test_cases(story)
        self.assertTrue(cases)
        self.assertTrue(all(case.feature_point == "Admin Portal" for case in cases))

    def test_jira_ac_blocks_ignore_summary_header(self) -> None:
        from skills.test_case.jira_read import _extract_acceptance_criteria

        description = (
            "Summary\n：後台新增活動Banner\n"
            "Background\n：需要後台管理\n"
            "AC 1：左側選單新增入口\nGiven Admin登入\nWhen 檢視選單\nThen 出現入口\n"
            'AC 2：列表支援狀態篩選\n{"type": "hardBreak"}\nGiven 進入列表\nThen 可篩選'
        )
        criteria = _extract_acceptance_criteria(description, {})
        self.assertEqual(len(criteria), 2)
        self.assertTrue(criteria[0].startswith("AC1:"))
        self.assertIn("左側選單", criteria[0])
        self.assertNotIn("Summary", criteria[0])

    def test_dedupe_skips_existing_titles(self) -> None:
        generated = [
            TestCase("A", "1", "ok", "functional", "MBPAS-1", "t"),
            TestCase("B", "1", "ok", "functional", "MBPAS-1", "t"),
            TestCase("a", "1", "ok", "functional", "MBPAS-1", "t"),
        ]
        created, skipped = partition_new_cases(generated, {"A"})
        self.assertEqual([c.title for c in created], ["B"])
        self.assertEqual(len(skipped), 2)

    def test_skill_writes_additive_rows(self) -> None:
        fake = FakeBitable()
        fake.records.append({"fields": {"Story Key": "MBPAS-1601", "Title": "使用 Email 成功登入"}})

        def reader(key: str) -> StoryContext:
            return StoryContext(
                key=key,
                type="Story",
                summary="Login flow",
                description="",
                acceptance_criteria=["User can log in"],
            )

        result = generate_test_cases_for_issue(
            project="mbpass",
            issue_key="MBPAS-1601",
            config={"projects": {"mbpass": {"test_case": {"base_app_token": "bas_test", "table_name": "Test Cases", "language": "zh-Hant"}}}},
            client=fake,
            story_reader=reader,
            designer_runner=_mock_design_runner(LOGIN_DESIGN),
        )
        self.assertEqual(result["status"], "completed")
        self.assertGreaterEqual(result["created"], 2)
        self.assertGreaterEqual(result["skipped_existing"], 1)
        self.assertIn("MBPAS-1601", result["view_name"])
        self.assertTrue(result["summary"])

    def test_skill_writes_spreadsheet_rows(self) -> None:
        fake = FakeSheets()

        def reader(key: str) -> StoryContext:
            return StoryContext(
                key=key,
                type="Story",
                summary="Login flow",
                description="",
                acceptance_criteria=["User can log in"],
            )

        result = generate_test_cases_for_issue(
            project="mbpass",
            issue_key="MBPAS-1601",
            config={
                "projects": {
                    "mbpass": {
                        "test_case": {
                            "destination": "sheet",
                            "spreadsheet_token": "test-a-spreadsheet",
                            "sheet_name": "PK03",
                            "sheet_template_id": "pk03-template",
                            "language": "zh-Hant",
                        }
                    }
                }
            },
            sheets_client=fake,
            story_reader=reader,
            designer_runner=_mock_design_runner(LOGIN_DESIGN),
        )
        self.assertEqual(result["status"], "completed")
        self.assertGreaterEqual(result["created"], 3)
        self.assertEqual(fake.copied, [{"sheetId": "sht1", "title": "MBPAS-1601 · Login flow"}])
        self.assertEqual(fake.cleared, [{"sheet_id": "sht1", "range_a1": "A1:O120"}])
        self.assertEqual(result["view_name"], "MBPAS-1601 · Login flow")
        self.assertEqual(
            fake.rows[0],
            [
                "卡link", "卡號標題", "设备/功能点", "用例 ID", "Path", "Test Summary",
                "Pre-condition", "Test Data", "Action", "Expected Result", "测试人",
                "測試結果", "測試日期", "備註", "Follow up",
            ],
        )
        for row in fake.rows[1:]:
            self.assertEqual(len(row), 15)
            self.assertEqual(row[0], "https://inspire.atlassian.net/browse/MBPAS-1601")
            self.assertEqual(row[1], "MBPAS-1601 · Login flow")
            self.assertEqual(row[2], "App")
            expected_path = {
                "使用 Email 成功登入": "Happy",
                "錯誤密碼時顯示登入失敗": "Sad",
                "登入頁顯示登入表單": "Happy",
            }[row[5]]
            self.assertEqual(row[4], expected_path)
            self.assertTrue(row[5])
            self.assertEqual(row[7], "")
            self.assertEqual(row[11], "待驗證")
            self.assertEqual(row[13], "")
        self.assertEqual(fake.dropdowns[0]["options"], ["Happy", "Alternative", "Sad", "Sad(Edge)"])
        self.assertEqual(fake.dropdowns[0]["colors"], ["#bacefd", "#fed4a4", "#b1e8fc", "#7edafb"])
        self.assertEqual("E2:E4", fake.dropdowns[0]["range_a1"])
        self.assertEqual(fake.dropdowns[1]["options"], ["待驗證", "驗證成功", "驗證失敗", "忽略"])
        self.assertEqual(fake.dropdowns[1]["colors"], ["#A3D0D6", "#B5CFBC", "#F9B0BD", "#E6C284"])
        self.assertEqual("L2:L4", fake.dropdowns[1]["range_a1"])
        self.assertEqual(fake.verified[0]["freeze_rows"], 1)
        self.assertEqual(fake.verified[0]["validation_options"], ["Happy", "Alternative", "Sad", "Sad(Edge)"])
        self.assertEqual(fake.verified[1]["validation_range"], "L2:L4")
        self.assertEqual(fake.verified[1]["validation_options"], ["待驗證", "驗證成功", "驗證失敗", "忽略"])
        self.assertIn("/sheets/test-a-spreadsheet?sheet=sht1", result["sheet_url"])

    def test_skill_reuses_existing_card_sheet_and_deduplicates_rows(self) -> None:
        fake = FakeSheets()

        def reader(key: str) -> StoryContext:
            return StoryContext(
                key=key,
                type="Story",
                summary="Login flow",
                description="",
                acceptance_criteria=["User can log in"],
            )

        config = {
            "projects": {
                "mbpass": {
                    "test_case": {
                        "destination": "sheet",
                        "spreadsheet_token": "test-a-spreadsheet",
                        "sheet_template_id": "pk03-template",
                        "language": "zh-Hant",
                    }
                }
            }
        }
        first = generate_test_cases_for_issue(
            project="mbpass",
            issue_key="MBPAS-1601",
            config=config,
            sheets_client=fake,
            story_reader=reader,
            designer_runner=_mock_design_runner(LOGIN_DESIGN),
        )
        second = generate_test_cases_for_issue(
            project="mbpass",
            issue_key="MBPAS-1601",
            config=config,
            sheets_client=fake,
            story_reader=reader,
            designer_runner=_mock_design_runner(LOGIN_DESIGN),
        )
        self.assertEqual(first["created"], 3)
        self.assertEqual(second["created"], 0)
        self.assertEqual(second["skipped_existing"], 3)
        self.assertEqual(len(fake.copied), 1)

    def test_feishu_sheet_format_uses_native_dimension_payload_and_readback(self) -> None:
        from feishu.sheets import FeishuSheets

        client = FeishuSheets.__new__(FeishuSheets)
        calls: list[tuple[str, str, dict[str, Any] | None]] = []

        def request(method: str, path: str, payload: dict[str, Any] | None = None) -> dict[str, Any]:
            calls.append((method, path, payload))
            if path.endswith("/metainfo"):
                return {"sheets": [{"sheetId": "sht1", "frozenRowCount": 1, "rowCount": 120}]}
            if "/dataValidation?" in path:
                return {"dataValidations": [{"conditionValues": ["待驗證", "驗證成功"]}]}
            return {}

        client._request = request
        self.assertEqual(120, client.get_sheet_row_count("spreadsheet", sheet_id="sht1"))
        client.format_sheet(
            "spreadsheet",
            sheet_id="sht1",
            column_widths=[(0, 80)],
            freeze_rows=1,
            bold_header=True,
            header_end_col="H",
            body_row_height=96,
            body_end_row=120,
        )
        client.verify_sheet_format(
            "spreadsheet",
            sheet_id="sht1",
            freeze_rows=1,
            validation_range="G2:G2000",
            validation_options=["待驗證", "驗證成功"],
        )

        dimension_calls = [call for call in calls if call[1].endswith("/dimension_range")]
        self.assertEqual("PUT", dimension_calls[0][0])
        self.assertEqual(1, dimension_calls[0][2]["dimension"]["startIndex"])
        self.assertEqual(2, dimension_calls[0][2]["dimension"]["endIndex"])
        self.assertEqual(80, dimension_calls[0][2]["dimensionProperties"]["fixedSize"])
        style_calls = [call for call in calls if call[1].endswith("/style")]
        self.assertEqual("11pt/1.5", style_calls[0][2]["appendStyle"]["style"]["font"]["fontSize"])
        self.assertEqual("10pt/1.5", style_calls[1][2]["appendStyle"]["style"]["font"]["fontSize"])
        freeze_call = next(call for call in calls if call[1].endswith("/sheets_batch_update"))
        self.assertEqual(1, freeze_call[2]["requests"][0]["updateSheet"]["properties"]["frozenRowCount"])
        self.assertTrue(any("/dataValidation?" in call[1] for call in calls))

    def test_feishu_pk03_template_operations_use_editor_tools(self) -> None:
        from feishu.sheets import FeishuSheets

        client = FeishuSheets.__new__(FeishuSheets)
        calls: list[tuple[str, str, dict[str, Any] | None]] = []

        def request(method: str, path: str, payload: dict[str, Any] | None = None) -> dict[str, Any]:
            calls.append((method, path, payload))
            if path.endswith("/metainfo"):
                return {"sheets": [{"sheetId": "new1", "title": "MBPAS-1601 · Login flow"}]}
            return {}

        client._request = request
        copied = client.copy_sheet(
            "test-a-spreadsheet",
            source_sheet_id="pk03-template",
            title="MBPAS-1601 · Login flow",
        )
        self.assertEqual(copied["sheetId"], "new1")
        client.clear_values(
            "test-a-spreadsheet",
            sheet_id="new1",
            range_a1="A1:O37",
        )
        client.set_values(
            "test-a-spreadsheet",
            sheet_id="new1",
            range_a1="A1:O2",
            values=[["卡link", "卡號標題"], ["https://example.test", "Card"]],
        )

        tool_calls = [call for call in calls if "/tools/invoke_write" in call[1]]
        self.assertEqual(len(tool_calls), 3)
        copy_input = json.loads(tool_calls[0][2]["input"])
        self.assertEqual(copy_input["operation"], "duplicate")
        self.assertEqual(copy_input["sheet_id"], "pk03-template")
        self.assertNotIn("target_index", copy_input)
        clear_input = json.loads(tool_calls[1][2]["input"])
        self.assertEqual(clear_input["clear_type"], "contents")
        set_input = json.loads(tool_calls[2][2]["input"])
        self.assertEqual(set_input["cells"][1][0]["value"], "https://example.test")

    def test_summary_uses_story_title_and_response_language(self) -> None:
        from skills.test_case.skill import format_summary

        summary = format_summary(
            {
                "issue_key": "MBPAS-1491",
                "story_title": "後台新增活動 Banner 管理",
                "generated": 2,
                "created": 2,
                "skipped_existing": 0,
                "test_case_counts": {"功能": 2},
                "sheet_url": "https://sheet/1",
            },
            "zh-Hant",
        )
        self.assertIn("MBPAS-1491 — 後台新增活動 Banner 管理", summary)
        self.assertIn("飛書測試用例表", summary)

    def test_broker_test_case_action_uses_request_agent_identity(self) -> None:
        ensure_definitions_loaded()
        mark = get_definition("mark")
        milchick = get_definition("milchick")
        assert mark is not None and milchick is not None
        self.assertNotIn("test_case.generate", mark.capabilities.actions)
        self.assertIn("test_case.generate", milchick.capabilities.actions)
        from unittest import mock

        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch.dict(os.environ, {"LUMEN_AGENTS_HOME": tmp}):
                with mock.patch("skills.test_case.skill.generate_test_cases_for_issue") as gen:
                    gen.return_value = {"status": "completed", "summary": "ok", "created": 1, "generated": 1}
                    broker = CapabilityBroker(
                        config={
                            "access": {
                                "allowed_chat_ids": ["oc1"],
                                "allowed_user_ids": ["ou_owner"],
                                "mutation_allowed_user_ids": ["ou_owner"],
                            }
                        }
                    )
                    for agent_id in ("milchick",):
                        receipt = broker.execute(
                            ActionRequest(
                                agent_id=agent_id,
                                action="test_case.generate",
                                project_slug="mbpass",
                                actor_user_id="ou_owner",
                                chat_id="oc1",
                                thread_id="",
                                source_message_id="om1",
                                trace_id="tr1",
                                resource={"issue_key": "MBPAS-1601"},
                                arguments={"issue_key": "MBPAS-1601", "chat_type": "group"},
                                explicit_authorization=True,
                            )
                        )
                        self.assertEqual(receipt.status, "succeeded")
                        self.assertEqual(gen.call_args.kwargs["generated_by"], agent_id)

    def test_scoped_test_case_action_queries_and_processes_each_story(self) -> None:
        from agents.security.adapters.test_case import execute_test_case_action

        request = ActionRequest(
            agent_id="milchick",
            action="test_case.generate",
            project_slug="mbpass",
            actor_user_id="ou_owner",
            chat_id="oc1",
            thread_id="omt1",
            source_message_id="om1",
            trace_id="tr1",
            arguments={"scope": "ready_for_qa", "user_message": "請把 JIRA Ready for QA 的 Story 生成測試用例"},
        )
        with mock.patch(
            "agents.security.adapters.jira._action_jira_config",
            return_value={"project_key": "MBPAS"},
        ), mock.patch(
            "agents.security.adapters.jira._query_workitems",
            return_value={
                "status": "completed",
                "items": [
                    {"issue_key": "MBPAS-1", "summary": "First"},
                    {"issue_key": "MBPAS-2", "summary": "Second"},
                ],
            },
        ), mock.patch(
            "skills.test_case.skill.generate_test_cases_for_issue",
            side_effect=[
                {"status": "completed", "generated": 2, "created": 2, "sheet_url": "https://sheet/1"},
                {"status": "failed", "code": "TEST_CASE_CONFIG_MISSING", "message": "missing sheet"},
            ],
        ) as generate:
            result = execute_test_case_action(request)

        self.assertEqual("partial", result["status"])
        self.assertEqual(2, result["count"])
        self.assertEqual(1, result["completed"])
        self.assertEqual(1, result["failed"])
        self.assertEqual(["MBPAS-1", "MBPAS-2"], [item["issue_key"] for item in result["items"]])
        self.assertIn("MBPAS-1 — First", result["summary"])
        self.assertIn("MBPAS-2 — Second", result["summary"])
        self.assertIn("已為", result["summary"])
        self.assertEqual("zh-Hant", result["response_language"])
        self.assertEqual(2, generate.call_count)
        self.assertEqual("zh-Hant", generate.call_args_list[0].kwargs["response_language"])

    def test_scoped_query_is_story_only(self) -> None:
        from agents.security.adapters.test_case import execute_test_case_action

        request = ActionRequest(
            agent_id="milchick",
            action="test_case.generate",
            project_slug="mbpass",
            actor_user_id="ou_owner",
            chat_id="oc1",
            thread_id="omt1",
            source_message_id="om1",
            trace_id="tr1",
            arguments={"scope": "ready_for_qa"},
        )
        with mock.patch(
            "agents.security.adapters.test_case._docs_root",
            return_value=Path("/tmp/workspace"),
        ), mock.patch(
            "agents.security.adapters.jira._action_jira_config",
            return_value={"project_key": "MBPAS"},
        ), mock.patch(
            "agents.security.adapters.jira._query_workitems",
            return_value={"status": "completed", "items": []},
        ) as query:
            execute_test_case_action(request)

        self.assertIn('issuetype = "Story"', query.call_args.kwargs["jql"])


class MilchickJobTests(unittest.TestCase):
    def test_technical_loop_waits_for_artifact_instead_of_claiming_completion(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            docs = Path(tmp) / "docs"
            story = docs / "stories" / "MBPAS-1503-recommendations"
            story.mkdir(parents=True)
            (story / "story.md").write_text("# MBPAS-1503\n", encoding="utf-8")
            (story / "metadata.json").write_text(
                json.dumps({"jiraKey": "MBPAS-1503", "businessStatus": "ready", "technicalStatus": "draft"}),
                encoding="utf-8",
            )
            from agents.mark.delivery_adapter import DeliveryActionAdapter

            state = DeliveryActionAdapter().loop_state(
                workspace=docs,
                story="MBPAS-1503",
                capability="loop.technical",
            )
            self.assertFalse(state["complete"])
            self.assertEqual("technical_plan_missing", state["reason"])

    def test_waiting_user_loop_is_visible_in_parent_summary(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            store = AgentJobStore(Path(tmp) / "jobs.sqlite3")
            broker = AgentJobBroker(store)
            parent = broker.create_parent(
                project="mbpass", requested_by="ou_owner", delegated_by="milchick",
                source_message_id="om1", chat_id="oc1", thread_id="omt1", trace_id="tr1",
            )
            child = broker.create_child(
                parent=parent, target_agent="mark", capability="loop.technical",
                input_data={"issue_key": "MBPAS-1503"},
            )
            child.status = "waiting_user"
            child.result = {"result": {"question": "Which repository should be used?"}}
            store.save(child)
            summary = broker.summarize(parent.job_id)
            self.assertEqual("waiting_user", summary["overall_state"])
            self.assertIn(child.job_id, summary["waiting_user"])

    def test_waiting_loop_matches_mark_question_reply_anchor(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            store = AgentJobStore(Path(tmp) / "jobs.sqlite3")
            parent = AgentJobBroker(store).create_parent(
                project="mbpass", requested_by="ou_owner", delegated_by="milchick",
                source_message_id="om-root", chat_id="oc1", thread_id="", trace_id="tr1",
            )
            child = AgentJobBroker(store).create_child(
                parent=parent, target_agent="mark", capability="loop.technical",
                input_data={"issue_key": "MBPAS-1503"},
            )
            child.status = "waiting_user"
            child.result = {"question_message_id": "om-question"}
            store.save(child)
            found = store.find_waiting_loop(
                agent_id="mark", chat_id="oc1", parent_id="om-question",
            )
            self.assertIsNotNone(found)
            self.assertEqual(child.job_id, found.job_id)
    def test_milchick_definition_registered(self) -> None:
        ensure_definitions_loaded()
        milchick = get_definition("milchick")
        assert milchick is not None
        self.assertEqual(milchick.role, "orchestrator")
        self.assertIn("agent.job.create", milchick.capabilities.actions)
        self.assertIn("jira.workitem.create", milchick.capabilities.actions)
        self.assertIn("test_case.generate", milchick.capabilities.actions)

    def test_job_dependency_and_summary(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            store = AgentJobStore(Path(tmp) / "jobs.sqlite3")
            broker = AgentJobBroker(store)
            parent = broker.create_parent(
                project="mbpass",
                requested_by="ou_owner",
                delegated_by="milchick",
                source_message_id="om1",
                chat_id="oc1",
                thread_id="th1",
                trace_id="tr1",
            )
            first = broker.create_child(
                parent=parent,
                target_agent="irving",
                capability="risk.resolve",
                input_data={"finding_id": "FIND-1"},
            )
            second = broker.create_child(
                parent=parent,
                target_agent="milchick",
                capability="test_case.generate",
                input_data={"issue_key": "MBPAS-1601"},
                depends_on=[first.job_id],
            )
            self.assertEqual(first.status, "ready")
            self.assertEqual(second.status, "queued")
            first.status = "completed"
            store.save(first)
            broker.refresh_dependencies(parent.job_id)
            second = store.get(second.job_id)
            assert second is not None
            self.assertEqual(second.status, "ready")
            summary = broker.summarize(parent.job_id)
            self.assertIn(summary["overall_state"], {"running", "completed", "blocked"})

    def test_quick_change_handoff_preserves_original_turn(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            store = AgentJobStore(Path(tmp) / "jobs.sqlite3")
            broker = AgentJobBroker(store)
            parent = broker.create_parent(
                project="mbpass",
                requested_by="ou_owner",
                delegated_by="milchick",
                source_message_id="om1",
                chat_id="oc1",
                thread_id="",
                trace_id="tr1",
            )
            child = broker.create_child(
                parent=parent,
                target_agent="mark",
                capability="delivery.quick_change",
                input_data={
                    "user_message": "Admin Portal 中的 Wording「輪播圖」改成「多圖」",
                    "image_keys": '["img_v3"]',
                    "chat_type": "group",
                },
            )
            with mock.patch(
                "agents.bridge.handle_agent_message",
                return_value={"status": "ok", "text": "Mark started the bounded change."},
            ) as handoff, mock.patch(
                "feishu.messenger.FeishuMessenger.safe_reply_text",
                return_value={"message_id": "om2"},
            ):
                completed = broker.execute_ready_child(child)

            self.assertEqual("completed", completed.status)
            handoff.assert_called_once()
            kwargs = handoff.call_args.kwargs
            self.assertEqual("mark", kwargs["agent_id"])
            self.assertIn("This task is handed to you", kwargs["text"])
            self.assertIn(child.input["user_message"], kwargs["text"])
            self.assertEqual("mbpass", kwargs["meta"]["_project_slug"])
            self.assertEqual('["img_v3"]', kwargs["meta"]["image_keys"])
            self.assertEqual("1", kwargs["meta"]["_nested_handoff"])
            self.assertEqual("1", kwargs["meta"]["_new_agent_turn"])

    def test_loop_handoff_preserves_original_turn(self) -> None:
        for capability in ("loop.business", "loop.technical"):
            with self.subTest(capability=capability):
                with tempfile.TemporaryDirectory() as tmp:
                    store = AgentJobStore(Path(tmp) / "jobs.sqlite3")
                    broker = AgentJobBroker(store)
                    parent = broker.create_parent(
                        project="mbpass",
                        requested_by="ou_owner",
                        delegated_by="milchick",
                        source_message_id="om1",
                        chat_id="oc1",
                        thread_id="",
                        trace_id="tr1",
                    )
                    child = broker.create_child(
                        parent=parent,
                        target_agent="mark",
                        capability=capability,
                        input_data={
                            "user_message": "把 MBPAS-1503 進行 Technical Plan",
                            "image_keys": '["img_v3"]',
                            "chat_type": "group",
                        },
                    )
                    with mock.patch(
                        "agents.bridge.handle_agent_message",
                        return_value={"status": "ok", "text": "Mark started the loop."},
                    ) as handoff, mock.patch(
                        "feishu.messenger.FeishuMessenger.safe_reply_text",
                        return_value={"message_id": "om2"},
                    ):
                        completed = broker.execute_ready_child(child)

                    self.assertEqual("waiting_user", completed.status)
                    handoff.assert_called_once()
                    kwargs = handoff.call_args.kwargs
                    self.assertEqual("mark", kwargs["agent_id"])
                    self.assertIn("[ORIGINAL USER INPUT]", kwargs["text"])
                    self.assertIn(child.input["user_message"], kwargs["text"])
                    expected_hint = "Business Loop" if capability == "loop.business" else "Technical Loop"
                    self.assertIn(expected_hint, kwargs["text"])
                    self.assertEqual("1", kwargs["meta"]["_nested_handoff"])


if __name__ == "__main__":
    unittest.main()
