from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Optional

from feishu.config import load_agents_config, read_lumen_env_var
from feishu.sheets import parse_spreadsheet_token


REQUIRED_FIELDS = (
    ("Story Key", 1),
    ("Story Title", 1),
    ("Title", 1),
    ("Steps", 1),
    ("Expected Result", 1),
    ("Type", 1),
    ("Status", 1),
    ("Verify Status", 3),
    ("Source Hash", 1),
    ("Generated At", 1),
    ("Generated By", 1),
)

HEADER_COLUMNS = [name for name, _ in REQUIRED_FIELDS]

def _load_pk03_template() -> dict[str, Any]:
    path = Path(__file__).with_name("pk03_template.json")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise RuntimeError(f"PK03 local template is unavailable: {path}") from exc
    if not isinstance(payload, dict) or not isinstance(payload.get("columns"), list):
        raise RuntimeError(f"PK03 local template is invalid: {path}")
    return payload


PK03_TEMPLATE = _load_pk03_template()
PK03_SHEET_HEADER_COLUMNS = tuple(
    str(column.get("name") or "").strip()
    for column in PK03_TEMPLATE["columns"]
    if isinstance(column, dict) and str(column.get("name") or "").strip()
)

# Keep the generic name as a compatibility alias for callers that imported it
# before the PK03 sheet became the canonical test-case layout.
SHEET_HEADER_COLUMNS = PK03_SHEET_HEADER_COLUMNS

DEFAULT_SHEET_TEMPLATE_NAME = str(PK03_TEMPLATE.get("name") or "PK03").strip() or "PK03"

VERIFY_STATUS_CANONICAL = ("pending", "passed", "failed", "ignored")

SUPPORTED_LANGUAGES = ("zh-Hant", "zh-Hans", "en")


def normalize_test_case_language(value: str) -> str:
    raw = str(value or "").strip().lower().replace("_", "-")
    if raw in {"zh-hant", "zh-tw", "zh-hk", "zh-mo", "zh", "zh-cht", "traditional", "zh-traditional"}:
        return "zh-Hant"
    if raw in {"zh-hans", "zh-cn", "zh-sg", "simplified"}:
        return "zh-Hans"
    if raw in {"en", "english"}:
        return "en"
    return "zh-Hant"


def normalize_destination(value: str) -> str:
    raw = str(value or "").strip().lower()
    if raw in {"sheet", "sheets", "spreadsheet", "excel"}:
        return "sheet"
    return "bitable"


def load_test_case_config(
    project: str,
    *,
    config: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    data = config if isinstance(config, dict) else load_agents_config()
    slug = str(project or "").strip().lower()
    projects = data.get("projects") if isinstance(data.get("projects"), dict) else {}
    project_cfg = projects.get(slug) if isinstance(projects.get(slug), dict) else {}
    test_case = project_cfg.get("test_case") if isinstance(project_cfg.get("test_case"), dict) else {}
    if not test_case:
        mark = data.get("mark") if isinstance(data.get("mark"), dict) else {}
        mark_tc = mark.get("test_case") if isinstance(mark.get("test_case"), dict) else {}
        nested = mark_tc.get("projects") if isinstance(mark_tc.get("projects"), dict) else {}
        test_case = nested.get(slug) if isinstance(nested.get(slug), dict) else {}
    destination = normalize_destination(str(test_case.get("destination") or "bitable"))
    language = normalize_test_case_language(str(test_case.get("language") or "zh-Hant"))
    base_host = str(test_case.get("feishu_base_host") or "inspiregroup.feishu.cn").strip() or "inspiregroup.feishu.cn"
    table_name = str(test_case.get("table_name") or test_case.get("sheet_name") or "Test Cases").strip() or "Test Cases"
    sheet_name = str(test_case.get("sheet_name") or test_case.get("table_name") or "Sheet1").strip() or "Sheet1"
    # PK03 is now a local, versioned layout specification.  Keep the legacy
    # return keys for callers that still inspect them, but never read a remote
    # template sheet ID or its environment variable again.
    sheet_template_id = ""
    sheet_template_id_env = ""
    sheet_template_name = DEFAULT_SHEET_TEMPLATE_NAME
    jira_base_url = str(test_case.get("jira_base_url") or "https://inspire.atlassian.net").strip().rstrip("/")

    app_token = str(test_case.get("base_app_token") or "").strip()
    token_env = str(test_case.get("base_app_token_env") or "").strip()
    if not app_token and token_env:
        app_token = os.environ.get(token_env, "").strip() or read_lumen_env_var(token_env).strip()

    spreadsheet_token = parse_spreadsheet_token(
        str(test_case.get("spreadsheet_token") or test_case.get("spreadsheet_url") or "").strip()
    )
    sheet_token_env = str(test_case.get("spreadsheet_token_env") or "").strip()
    if not spreadsheet_token and sheet_token_env:
        spreadsheet_token = parse_spreadsheet_token(
            os.environ.get(sheet_token_env, "").strip() or read_lumen_env_var(sheet_token_env).strip()
        )
    if destination == "sheet" and not spreadsheet_token and app_token:
        spreadsheet_token = parse_spreadsheet_token(app_token)

    return {
        "project": slug,
        "destination": destination,
        "base_app_token": app_token,
        "spreadsheet_token": spreadsheet_token,
        "table_name": table_name if destination == "bitable" else sheet_name,
        "sheet_name": sheet_name,
        "sheet_template_id": sheet_template_id,
        "sheet_template_id_env": sheet_template_id_env,
        "sheet_template_name": sheet_template_name,
        "jira_base_url": jira_base_url,
        "view_strategy": str(test_case.get("view_strategy") or "story"),
        "language": language,
        "feishu_base_host": base_host,
        "raw": test_case,
    }
