from __future__ import annotations

import os
from typing import Any, Optional

from feishu.config import load_agents_config, read_lumen_env_var
from feishu.sheets import parse_spreadsheet_token


REQUIRED_FIELDS = (
    ("Story Key", 1),
    ("Story Title", 1),
    ("Title", 1),
    ("Steps", 1),
    ("Expected Result", 1),
    ("Type", 1),
    ("Status", 1),
    ("Verify Status", 3),
    ("Source Hash", 1),
    ("Generated At", 1),
    ("Generated By", 1),
)

HEADER_COLUMNS = [name for name, _ in REQUIRED_FIELDS]

PK03_SHEET_HEADER_COLUMNS = (
    "卡link",
    "卡號標題",
    "设备/功能点",
    "用例 ID",
    "Path",
    "Test Summary",
    "Pre-condition",
    "Test Data",
    "Action",
    "Expected Result",
    "测试人",
    "測試結果",
    "測試日期",
    "備註",
    "Follow up",
)

# Keep the generic name as a compatibility alias for callers that imported it
# before the PK03 sheet became the canonical test-case layout.
SHEET_HEADER_COLUMNS = PK03_SHEET_HEADER_COLUMNS

DEFAULT_SHEET_TEMPLATE_NAME = "PK03"

VERIFY_STATUS_CANONICAL = ("pending", "passed", "failed", "ignored")

SUPPORTED_LANGUAGES = ("zh-Hant", "zh-Hans", "en")


def normalize_test_case_language(value: str) -> str:
    raw = str(value or "").strip().lower().replace("_", "-")
    if raw in {"zh-hant", "zh-tw", "zh-hk", "zh-mo", "zh", "zh-cht", "traditional", "zh-traditional"}:
        return "zh-Hant"
    if raw in {"zh-hans", "zh-cn", "zh-sg", "simplified"}:
        return "zh-Hans"
    if raw in {"en", "english"}:
        return "en"
    return "zh-Hant"


def normalize_destination(value: str) -> str:
    raw = str(value or "").strip().lower()
    if raw in {"sheet", "sheets", "spreadsheet", "excel"}:
        return "sheet"
    return "bitable"


def load_test_case_config(
    project: str,
    *,
    config: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    data = config if isinstance(config, dict) else load_agents_config()
    slug = str(project or "").strip().lower()
    projects = data.get("projects") if isinstance(data.get("projects"), dict) else {}
    project_cfg = projects.get(slug) if isinstance(projects.get(slug), dict) else {}
    test_case = project_cfg.get("test_case") if isinstance(project_cfg.get("test_case"), dict) else {}
    if not test_case:
        mark = data.get("mark") if isinstance(data.get("mark"), dict) else {}
        mark_tc = mark.get("test_case") if isinstance(mark.get("test_case"), dict) else {}
        nested = mark_tc.get("projects") if isinstance(mark_tc.get("projects"), dict) else {}
        test_case = nested.get(slug) if isinstance(nested.get(slug), dict) else {}
    destination = normalize_destination(str(test_case.get("destination") or "bitable"))
    language = normalize_test_case_language(str(test_case.get("language") or "zh-Hant"))
    base_host = str(test_case.get("feishu_base_host") or "inspiregroup.feishu.cn").strip() or "inspiregroup.feishu.cn"
    table_name = str(test_case.get("table_name") or test_case.get("sheet_name") or "Test Cases").strip() or "Test Cases"
    sheet_name = str(test_case.get("sheet_name") or test_case.get("table_name") or "Sheet1").strip() or "Sheet1"
    sheet_template_id = str(test_case.get("sheet_template_id") or "").strip()
    sheet_template_id_env = str(test_case.get("sheet_template_id_env") or "").strip()
    if not sheet_template_id and sheet_template_id_env:
        sheet_template_id = (
            os.environ.get(sheet_template_id_env, "").strip()
            or read_lumen_env_var(sheet_template_id_env).strip()
        )
    sheet_template_name = str(
        test_case.get("sheet_template_name") or DEFAULT_SHEET_TEMPLATE_NAME
    ).strip() or DEFAULT_SHEET_TEMPLATE_NAME
    jira_base_url = str(test_case.get("jira_base_url") or "https://inspire.atlassian.net").strip().rstrip("/")

    app_token = str(test_case.get("base_app_token") or "").strip()
    token_env = str(test_case.get("base_app_token_env") or "").strip()
    if not app_token and token_env:
        app_token = os.environ.get(token_env, "").strip() or read_lumen_env_var(token_env).strip()

    spreadsheet_token = parse_spreadsheet_token(
        str(test_case.get("spreadsheet_token") or test_case.get("spreadsheet_url") or "").strip()
    )
    sheet_token_env = str(test_case.get("spreadsheet_token_env") or "").strip()
    if not spreadsheet_token and sheet_token_env:
        spreadsheet_token = parse_spreadsheet_token(
            os.environ.get(sheet_token_env, "").strip() or read_lumen_env_var(sheet_token_env).strip()
        )
    if destination == "sheet" and not spreadsheet_token and app_token:
        spreadsheet_token = parse_spreadsheet_token(app_token)

    return {
        "project": slug,
        "destination": destination,
        "base_app_token": app_token,
        "spreadsheet_token": spreadsheet_token,
        "table_name": table_name if destination == "bitable" else sheet_name,
        "sheet_name": sheet_name,
        "sheet_template_id": sheet_template_id,
        "sheet_template_id_env": sheet_template_id_env,
        "sheet_template_name": sheet_template_name,
        "jira_base_url": jira_base_url,
        "view_strategy": str(test_case.get("view_strategy") or "story"),
        "language": language,
        "feishu_base_host": base_host,
        "raw": test_case,
    }
