from __future__ import annotations

import hashlib
import re
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any

from skills.test_case.localization import localize_test_case_type, localize_verify_status, normalize_case_type


CASE_TYPES = (
    "functional",
    "navigation",
    "filter",
    "permission",
    "validation",
    "state_transition",
    "boundary",
    "empty_state",
    "ui",
    "compatibility",
)


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def normalize_title(title: str) -> str:
    text = re.sub(r"\s+", " ", str(title or "").strip().lower())
    return text


def source_hash(*, story_key: str, title: str, steps: str, expected: str) -> str:
    payload = f"{story_key}|{normalize_title(title)}|{steps}|{expected}"
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


def format_ac_refs(ac_refs: list[str]) -> str:
    refs: list[str] = []
    seen: set[str] = set()
    for item in ac_refs or []:
        ref = str(item or "").strip().upper().replace(" ", "")
        if not ref or ref in seen:
            continue
        seen.add(ref)
        refs.append(ref)
    return ", ".join(refs)


def join_numbered(lines: list[str]) -> str:
    items = [str(line or "").strip() for line in lines if str(line or "").strip()]
    return "\n".join(f"{idx}. {line}" for idx, line in enumerate(items, start=1))


def join_lines(lines: list[str]) -> str:
    return "\n".join(str(line or "").strip() for line in lines if str(line or "").strip())


@dataclass
class StoryContext:
    key: str
    type: str
    summary: str
    description: str
    acceptance_criteria: list[str] = field(default_factory=list)
    comments: list[dict[str, Any]] = field(default_factory=list)
    attachments: list[dict[str, Any]] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class TestCaseDraft:
    ac_refs: list[str]
    title: str
    preconditions: list[str]
    steps: list[str]
    expected_results: list[str]
    case_type: str
    rationale: str = ""
    feature_point: str = ""
    test_data: list[str] = field(default_factory=list)


@dataclass
class TestCase:
    title: str
    steps: str
    expected_result: str
    case_type: str
    story_key: str
    story_title: str
    ac_refs: list[str] = field(default_factory=list)
    preconditions: str = ""
    feature_point: str = ""
    test_data: str = ""
    status: str = "Active"
    source_hash: str = ""
    generated_at: str = ""
    generated_by: str = "mark"

    def ensure_meta(self) -> None:
        if not self.generated_at:
            self.generated_at = utc_now()
        canonical = normalize_case_type(self.case_type) or str(self.case_type or "").strip().lower()
        if canonical:
            self.case_type = canonical
        if not self.source_hash:
            self.source_hash = source_hash(
                story_key=self.story_key,
                title=self.title,
                steps=self.steps,
                expected=self.expected_result,
            )

    def to_fields(self, language: str = "zh-Hant") -> dict[str, Any]:
        self.ensure_meta()
        return {
            "Story Key": self.story_key,
            "Story Title": self.story_title,
            "Title": self.title,
            "Steps": self.steps,
            "Expected Result": self.expected_result,
            "Type": self.case_type,
            "Status": self.status,
            "Verify Status": localize_verify_status("pending", language),
            "Source Hash": self.source_hash,
            "Generated At": self.generated_at,
            "Generated By": self.generated_by,
        }

    def to_sheet_fields(self, language: str = "zh-Hant") -> dict[str, Any]:
        self.ensure_meta()
        return {
            "AC": format_ac_refs(self.ac_refs),
            "Title": self.title,
            "Preconditions": self.preconditions,
            "Steps": self.steps,
            "Expected Result": self.expected_result,
            "Type": localize_test_case_type(self.case_type, language),
            "Verify Status": localize_verify_status("pending", language),
            "Note": "",
        }
